rpg/board/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('advertisement/<int:pk>/', views.advertisement_detail, name='advertisement_detail'),
    path('advertisement/new/', views.create_advertisement, name='create_advertisement'),
    path('advertisement/<int:pk>/create_response/', views.create_response, name='create_response'),
    path('user/dashboard/', views.user_dashboard, name='user_dashboard'),
    path('delete_response/<int:pk>/', views.delete_response, name='delete_response'),
    path('accept_response/<int:pk>/', views.accept_response, name='accept_response'),
]

rpg/rpg/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('board.urls')),
    path('tinymce/', include('tinymce.urls')),
]

rpg/board/models.py
from django.db import models
from django.contrib.auth.models import User

class Category(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Advertisement(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

class Response(models.Model):
    advertisement = models.ForeignKey(Advertisement, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    accepted = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.user.username} - {self.advertisement.title}'

rpg/board/forms.py
from tinymce.widgets import TinyMCE
from django import forms
from .models import Advertisement, Response, Category

class AdvertisementForm(forms.ModelForm):
    content = forms.CharField(widget=TinyMCE())

    class Meta:
        model = Advertisement
        fields = ['title', 'content', 'category']
        widgets = {
            'title': forms.TextInput(attrs={'placeholder': 'Заголовок объявления'}),
            'category': forms.Select(),
        }
        labels = {
            'title': '',
            'content': '',
            'category': '',
        }

class ResponseForm(forms.ModelForm):
    content = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Напишите комментарий...'}), label='')

    class Meta:
        model = Response
        fields = ['content']
        

rpg/board/views.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, get_object_or_404, redirect
from .models import Advertisement, Response
from .forms import AdvertisementForm, ResponseForm
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.conf import settings
from django.contrib.auth.models import User

#Главная
def index(request):
    advertisements_list = Advertisement.objects.all()
    paginator = Paginator(advertisements_list, 15)  # Пагинация - 15 объявлений

    page = request.GET.get('page')
    try:
        advertisements = paginator.page(page)
    except PageNotAnInteger:
        advertisements = paginator.page(1)
    except EmptyPage:
        advertisements = paginator.page(paginator.num_pages)

    response_forms = {ad.id: ResponseForm() for ad in advertisements}

    context = {
        'advertisements': advertisements,
        'response_forms': response_forms,
    }
    return render(request, 'board/index.html', context)

#Создать объявление
@login_required
def create_advertisement(request):
    if request.method == 'POST':
        form = AdvertisementForm(request.POST)
        if form.is_valid():
            advertisement = form.save(commit=False)
            advertisement.user = request.user
            advertisement.save()
            return redirect('advertisement_detail', pk=advertisement.pk)
    else:
        form = AdvertisementForm()
    return render(request, 'board/create_advertisement.html', {'form': form})

def advertisement_detail(request, pk):
    advertisement = get_object_or_404(Advertisement, pk=pk)
    return render(request, 'board/advertisement_detail.html', {'advertisement': advertisement})

#Создание комментария
@login_required
def create_response(request, pk):
    advertisement = get_object_or_404(Advertisement, pk=pk)
    if request.method == 'POST':
        form = ResponseForm(request.POST)
        if form.is_valid():
            response = form.save(commit=False)
            response.user = request.user
            response.advertisement = advertisement
            response.save()
            send_mail(
                'Новый ответ: RPG',
                f'Получен новый ответ на ваше объявление "{advertisement.title}".',
                settings.EMAIL_HOST_USER,
                [advertisement.user.email],
                fail_silently=False,
            )
            return redirect('advertisement_detail', pk=advertisement.pk)
    else:
        form = ResponseForm()
    return render(request, 'board/create_response.html', {'form': form, 'advertisement': advertisement})


@login_required
def delete_response(request, pk):
    response = get_object_or_404(Response, pk=pk)
    if response.advertisement.user == request.user:
        response.delete()
    return redirect('user_dashboard')

@login_required
def accept_response(request, pk):
    response = get_object_or_404(Response, pk=pk)
    if response.advertisement.user == request.user:
        response.accepted = True
        response.save()
        send_mail(
            'Ваш отклик принят',
            f'Ваш отклик на объявление "{response.advertisement.title}" был принят.',
            settings.EMAIL_HOST_USER,
            [response.user.email],
            fail_silently=False,
        )
    return redirect('user_dashboard')


#Пользовательская страница
def user_dashboard(request):
    # Получение данных
    user_advertisements = Advertisement.objects.filter(user=request.user).order_by('-created_at')
    advertisement_paginator = Paginator(user_advertisements, 5)  # 5 на страницу

    page = request.GET.get('page')
    try:
        advertisements = advertisement_paginator.page(page)
    except PageNotAnInteger:
        advertisements = advertisement_paginator.page(1)
    except EmptyPage:
        advertisements = advertisement_paginator.page(advertisement_paginator.num_pages)

    # Получение комментов
    user_responses = Response.objects.filter(user=request.user).order_by('-created_at')
    response_paginator = Paginator(user_responses, 5)

    response_page = request.GET.get('response_page')
    try:
        responses = response_paginator.page(response_page)
    except PageNotAnInteger:
        responses = response_paginator.page(1)
    except EmptyPage:
        responses = response_paginator.page(response_paginator.num_pages)

    context = {
        'advertisements': advertisements,
        'responses': responses,
    }

    return render(request, 'board/user_dashboard.html', context)

rpg/board/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <title>RPG ADVBoard</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'board/styles.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap"
        rel="stylesheet">
    <link rel="stylesheet" href="{% static 'tinymce/skins/ui/oxide/skin.min.css' %}">

</head>

<body>
    <nav>
        <div class="container">
            <div class="login-block">
                <a class="logo" href="/">
                    RPG
                </a>
                <ul>
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'user_dashboard' %}">Мой профиль</a></li>
                    <li><a href="{% url 'account_logout' %}">Выйти из аккаунта</a></li>
                    <li><a href="{% url 'create_advertisement' %}">Создать новое объявление</a></li>
                    {% else %}
                    <li><a href="{% url 'account_login' %}">Вход</a></li>
                    <li><a href="{% url 'account_signup' %}">Регистрация</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    {% block content %}
    {% endblock %}
    <script src="{% static 'js/scripts.js' %}"></script>
</body>

</html>

rpg/board/templates/board/advertisement_detail.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <a href="/" class="breadcrump"> ← Вернуться на главную страницу объявлений</a>
    <h1>{{ advertisement.title }}</h1>
    <p><strong>Категория:</strong> {{ advertisement.category.name }}</p>
    <p><strong>Содержимое:</strong> {{ advertisement.content|safe }}</p>
    <p><strong>Автор:</strong> {{ advertisement.user.username }}</p>
    <p><strong>Дата создания:</strong> {{ advertisement.created_at }}</p>

    <div class="comment">Ответы</div>
    <ul class="comment-section">
        {% for response in advertisement.response_set.all %}
        <li><strong>{{ response.user.username }}:</strong> {{ response.content }} ({{ response.created_at }})</li>
        {% empty %}
        <li>Нет ответов на это объявление.</li>
        {% endfor %}
    </ul>

    {% if user.is_authenticated %}
    <form method="post" action="{% url 'create_response' advertisement.pk %}">
        {% csrf_token %}
        {{ response_form.as_p }}
        <button type="submit">Добавить комментарий</button>
    </form>
    {% else %}
    <p>Вы должны <a href="{% url 'login' %}">войти</a>, чтобы оставить ответ.</p>
    {% endif %}
</div>
{% endblock %}

rpg/board/templates/board/create_advertisement.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="container">
    <h1>Создать новое объявление</h1>
    <p>Заполните необходимые поля:</p>

    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Создать</button>
        </form>
    </div>
</div>

<script src="{% static 'tinymce/tinymce.min.js' %}"></script>
<script>
    tinymce.init({
        selector: 'textarea',
        height: 500,
        menubar: false,
        plugins: [
            'advlist autolink lists link image charmap print preview anchor',
            'searchreplace visualblocks code fullscreen',
            'insertdatetime media table paste code help wordcount'
        ],
        toolbar: 'undo redo | formatselect | bold italic backcolor | \
                  alignleft aligncenter alignright alignjustify | \
                  bullist numlist outdent indent | removeformat | help',
        image_advtab: true,
        content_css: [
            '{% static "css/styles.css" %}',  // Подключение стилей вашего сайта
            'https://cdnjs.cloudflare.com/ajax/libs/tinymce/5.10.4/themes/silver/theme.min.css'
        ],
    });
</script>


{% endblock %}

rpg/board/templates/board/create_response.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <a href="/" class="breadcrump"> ← Вернуться на главную страницу объявлений</a>
    <h1>Оставить комментарий к "{{ advertisement.title }}"</h1>
    <form method="post" class="myform">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Отправить</button>
    </form>
</div>
{% endblock %}

rpg/board/templates/board/index.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <h1>Добро пожаловать на RPG-ADV!</h1>
    <p>Крупнейшая площадка объявлений по вселенной RPG</p>

    <div class="feed">
        <h2>Доступные объявления:</h2>
        {% for ad in advertisements %}
        <div class="feed-item">
            <div class="feed-item_caption">{{ ad.title }}</div>
            <div class="feed-date">{{ ad.created_at }}</div>
            <p class="feed-item_descr">{{ ad.content|safe }}</p>

            {% if user.is_authenticated %}
            <div class="comment">Комментарии:</div>
            <ul class="comment-section">
                {% for comment in ad.response_set.all %}
                <li><span class="response">{{ comment.user.username }}</span>: {{ comment.content }}</li>
                {% empty %}
                <li class="no-comment">К этому объявлению еще нет комментариев</li>
                {% endfor %}
            </ul>
            <a href="{% url 'create_response' ad.id %}" class="leave-comment">Оставить комментарий</a>
            {% else %}
            <p>Войдите, чтобы оставить комментарий.</p>
            {% endif %}
        </div>
        {% endfor %}
    </div>

    <div class="pagination">
        <span class="step-links">
            {% if advertisements.has_previous %}
            <a href="?page=1">&laquo; 1</a>
            <a href="?page={{ advertisements.previous_page_number }}">←</a>
            {% endif %}

            <span class="current">
                Стр. {{ advertisements.number }} из {{ advertisements.paginator.num_pages }}.
            </span>

            {% if advertisements.has_next %}
            <a href="?page={{ advertisements.next_page_number }}">→</a>
            <a href="?page={{ advertisements.paginator.num_pages }}">{{ advertisements.paginator.num_pages }}
                &raquo;</a>
            {% endif %}
        </span>
    </div>
</div>
{% endblock %}

rpg/board/templates/board/user_dashboard.html
{% extends "base.html" %}
{% block content %}

<div class="container">
    <div class="cols">
        <div class="col">
            <div class="col-title">Ваши объявления</div>
            {% if advertisements %}
            <ul class="items">

                {% for ad in advertisements %}
                <li class="feed-item">
                    <div><strong>{{ ad.title }}</strong></div>
                    <p><strong>Категория:</strong> {{ ad.category.name }}</p>
                    <p>Создано: {{ ad.created_at }}</p>
                    <a href="{% url 'advertisement_detail' ad.pk %}" class="leave-comment">Перейти к объявлению</a>
                    <div class="comment">Отклики на это объявление:</div>
                    <ul class="comment-section">
                        {% for response in ad.response_set.all %}
                        <li>
                            <span class="response">{{ response.user.username }}</span>: {{ response.content }}
                            {% if response.accepted %}
                            <p>Отклик принят</p>
                            {% else %}
                            <form method="post" action="{% url 'accept_response' response.pk %}"
                                style="display: inline;">
                                {% csrf_token %}
                                <button type="submit">Принять</button>
                            </form>
                            <form method="post" action="{% url 'delete_response' response.pk %}"
                                style="display: inline;">
                                {% csrf_token %}
                                <button type="submit">Удалить</button>
                            </form>
                            {% endif %}
                        </li>
                        {% empty %}
                        <li>К этому объявлению еще нет откликов</li>
                        {% endfor %}
                    </ul>
                </li>
                {% endfor %}

            </ul>
            <div class="pagination">
                <span class="step-links">
                    {% if advertisements.has_previous %}
                    <a href="?page=1">&laquo; 1</a>
                    <a href="?page={{ advertisements.previous_page_number }}">←</a>
                    {% endif %}

                    <span class="current">
                        Стр. {{ advertisements.number }} из {{ advertisements.paginator.num_pages }}.
                    </span>

                    {% if advertisements.has_next %}
                    <a href="?page={{ advertisements.next_page_number }}">→</a>
                    <a href="?page={{ advertisements.paginator.num_pages }}">{{ advertisements.paginator.num_pages }}
                        &raquo;</a>
                    {% endif %}
                </span>
            </div>
            {% else %}
            <p>У вас еще нет объявлений.</p>
            {% endif %}
        </div>
        <div class="col">
            <div class="col-title">Ваши отклики на объявления</div>
            {% if responses %}
            <ul class="items">
                {% for response in responses %}
                <li class="feed-item">
                    <p>На объявление: <strong><a class="to-link"
                                href="{% url 'advertisement_detail' response.advertisement.pk %}">
                                {{response.advertisement.title }}</a></strong></p>
                    <p>Содержание отклика: {{ response.content }}</p>
                </li>
                {% endfor %}
            </ul>
            <div class="pagination">
                <span class="step-links">
                    {% if responses.has_previous %}
                    <a href="?response_page=1">&laquo; 1</a>
                    <a href="?response_page={{ responses.previous_page_number }}">← </a>
                    {% endif %}

                    <span class="current">
                        Стр. {{ responses.number }} из {{ responses.paginator.num_pages }}
                    </span>

                    {% if responses.has_next %}
                    <a href="?response_page={{ responses.next_page_number }}"> →</a>
                    <a href="?response_page={{ responses.paginator.num_pages }}">{{ responses.paginator.num_pages }}
                        &raquo;</a>
                    {% endif %}
                </span>
            </div>
            {% else %}
            <p>Вы еще не оставили ни одного отклика.</p>
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}